version: 1
update_configs:

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "to-release"
    commit_message:
      prefix: "chore"

    # Apply default label to created
    # pull requests
    default_labels:
      - "updgrade-deps"
